fileVersion: 1
id: "37"
mappingDefinitions:
  SRC:
    database: OBODNAR_DEV
    schema: TASTY_BYTES
  BRONZE:
    database: OBODNAR_DEV
    schema: BRONZE
  GOLD:
    database: OBODNAR_DEV
    schema: GOLD
  PUBLIC:
    database: OBODNAR_DEV
    schema: PUBLIC
  SILVER:
    database: OBODNAR_DEV
    schema: SILVER
  STAGING:
    database: OBODNAR_DEV
    schema: STAGING
  TARGET:
    database: OBODNAR_DEV
    schema: TARGET
  TASTY_BYTES:
    database: OBODNAR_DEV
    schema: TASTY_BYTES
  WEATHER:
    database: OBODNAR_DEV
    schema: WEATHER
name: Dev Environment
type: Environment
