fileVersion: 1
id: "36"
mappingDefinitions:
  SRC:
    database: OBODNAR_DEV
    schema: TASTY_BYTES
  STAGING:
    database: OBODNAR_DEV
    schema: STAGING
  BRONZE:
    database: OBODNAR_DEV
    schema: BRONZE
  GOLD:
    database: OBODNAR_DEV
    schema: GOLD
  PUBLIC:
    database: OBODNAR_DEV
    schema: PUBLIC
  SILVER:
    database: OBODNAR_DEV
    schema: SILVER
  TARGET:
    database: OBODNAR_DEV
    schema: TARGET
  TASTY_BYTES:
    database: OBODNAR_DEV
    schema: TASTY_BYTES
  WEATHER:
    database: OBODNAR_DEV
    schema: WEATHER
name: Replicate
type: Environment
